version: '3'
services:
  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_DB=test
    ports:
      - "8086:8086"
    volumes:
      - influxdb_lib:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "8030:3000"
    volumes:
      - grafana_lib:/var/lib/grafana
    depends_on:
      - influxdb

  mongo:
    image: mongo:4.2.8
    container_name: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=data
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mongo-lib:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    depends_on:
      - mongo

volumes:
  grafana_lib:
  influxdb_lib:
  mongo-lib: