name: ts-data-analyzer

on:
  push:
    paths-ignore:
      - ".storybook/**"
      - "stories/**"
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Build Image
        run: npm run docker-build-up
        env:
          NPM_TOKEN: ${{ secrets.ACTIONSTOKEN }}
      - name: API Test
        run: |
          bash init_db
          npm run api-test
      - name: login github, push image to github repository
        if: github.ref == 'refs/heads/main'
        env:
          IMAGE_NAME: ts-data-analyzer
        run: |
          echo "${{ secrets.ACTIONSTOKEN }}" | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          IMAGE_ID=docker.pkg.github.com/nakayamaron-dev/ts-data-analyzer/$IMAGE_NAME
          IMAGE_TAG=$(echo $GITHUB_REF | sed -e "s#refs/heads/##g")
          IMAGE_TAG_WITH_TIME=$IMAGE_TAG`date +".%Y%m%d.%H%M"`
          echo IMAGE_ID=$IMAGE_ID
          echo IMAGE_TAG=$IMAGE_TAG
          echo IMAGE_TAG_WITH_TIME=$IMAGE_TAG_WITH_TIME
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_TAG_WITH_TIME
          docker push $IMAGE_ID:$IMAGE_TAG_WITH_TIME
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_TAG
          docker push $IMAGE_ID:$IMAGE_TAG
